config/routes.rb
Rails.application.routes.draw do

  resources :eventos

  resources :editoras
  
  resources :basic_publications, :path => 'publications'

  resources :profiles do
    resources :basic_publications, :path => 'publications'
  end

  get 'pages/home'

  get 'pages/help'

  devise_for :users

  root 'pages#home'

end

app/models/basic_publication.rb
class BasicPublication < ActiveRecord::Base
  belongs_to :profile
end

app/controllers/basic_publications_controller.rb
class BasicPublicationsController < ApplicationController
  before_action :set_basic_publication, only: [:show, :edit, :update, :destroy]

  # GET /basic_publications
  # GET /basic_publications.json
  def index
    @basic_publications = BasicPublication.all
  end

  # GET /basic_publications/1
  # GET /basic_publications/1.json
  def show
  end

  # GET /basic_publications/new
  def new
    @basic_publication = BasicPublication.new
    @profile = current_user.profile
  end

  # GET /basic_publications/1/edit
  def edit
  end

  # POST /basic_publications
  # POST /basic_publications.json
  def create
    @basic_publication = BasicPublication.new(basic_publication_params)

    respond_to do |format|
      if @basic_publication.save
        format.html { redirect_to @basic_publication.profile, notice: 'Publicação criada com sucesso' }
        format.json { render :show, status: :created, location: @basic_publication }
      else
        format.html { render :new }
        format.json { render json: @basic_publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basic_publications/1
  # PATCH/PUT /basic_publications/1.json
  def update
    respond_to do |format|
      if @basic_publication.update(basic_publication_params)
        format.html { redirect_to @basic_publication.profile, notice: 'Publicação salva com sucesso' }
        format.json { render :show, status: :ok, location: @basic_publication }
      else
        format.html { render :edit }
        format.json { render json: @basic_publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basic_publications/1
  # DELETE /basic_publications/1.json
  def destroy
    @basic_publication.destroy
    respond_to do |format|
      format.html { redirect_to basic_publications_url, notice: 'Publicação deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basic_publication
      @basic_publication = BasicPublication.find(params[:id])
      @profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basic_publication_params
      params.require(:basic_publication).permit(:profile_id, :title, :year, :country, :language, :webpage, :english_title, :publication_type)
    end
end

app/helpers/basic_publications_helper.rb
module BasicPublicationsHelper
end

app/views/basic_publications/_form.html.erb
<%= form_for(@basic_publication) do |f| %>
  <% if @basic_publication.errors.any? %>
    <div id="error_explanation">
      <h2>Os <%= pluralize(@basic_publication.errors.count, "Erro") %> não permitiram que a publicação fosse gravada:</h2>

      <ul>
      <% @basic_publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.number_field :profile_id, :class => 'hidden', :value => @profile.id %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :webpage %><br>
    <%= f.text_field :webpage %>
  </div>
  <div class="field">
    <%= f.label :english_title %><br>
    <%= f.text_field :english_title %>
  </div>
  <div class="field">
    <%= f.label :publication_type %><br>
    <%= f.text_field :publication_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basic_publications/_publication_info.html.erb
	<div class="row-fluid section-header">
		<h3 class="span6">Publicações</h3>
		<div class="span6">
			<%= link_to new_profile_basic_publication_path(@profile), :class => "btn btn-primary pull-right" do %>
				Nova publicação
			<% end %>
		</div>
	</div>	
	<ul class="unstyled">
		<% @publications.each do |publication| %>					
			<li><%= link_to publication.title, profile_basic_publication_path(@profile, publication)%></li>		
		<% end %>
	</ul>

app/views/basic_publications/edit.html.erb
<h1>Editar publicação:</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @basic_publication.profile %> |
<%= link_to 'Voltar', profile_path(@basic_publication.profile) %>

app/views/basic_publications/index.html.erb
<h1>Listing basic_publications</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Title</th>
      <th>Year</th>
      <th>Country</th>
      <th>Language</th>
      <th>Webpage</th>
      <th>English title</th>
      <th>Publication type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basic_publications.each do |basic_publication| %>
      <tr>
        <td><%= basic_publication.profile_id %></td>
        <td><%= basic_publication.title %></td>
        <td><%= basic_publication.year %></td>
        <td><%= basic_publication.country %></td>
        <td><%= basic_publication.language %></td>
        <td><%= basic_publication.webpage %></td>
        <td><%= basic_publication.english_title %></td>
        <td><%= basic_publication.publication_type %></td>
        <td><%= link_to 'Show', basic_publication %></td>
        <td><%= link_to 'Edit', edit_basic_publication_path(basic_publication) %></td>
        <td><%= link_to 'Destroy', basic_publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basic publication', new_basic_publication_path %>

app/views/basic_publications/new.html.erb
<h1>Criar nova publicação</h1>

<%= render 'form' %>

<%= link_to 'Voltar', profile_path(@profile.id) %>

app/views/basic_publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @basic_publication.profile.name %>
</p>

<p>
  <strong>Título:</strong>
  <%= @basic_publication.title %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @basic_publication.year %>
</p>

<p>
  <strong>País:</strong>
  <%= @basic_publication.country %>
</p>

<p>
  <strong>Idioma:</strong>
  <%= @basic_publication.language %>
</p>

<p>
  <strong>Página web:</strong>
  <%= @basic_publication.webpage %>
</p>

<p>
  <strong>Título em inglês:</strong>
  <%= @basic_publication.english_title %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @basic_publication.publication_type %>
</p>

<%= link_to 'Editar', edit_basic_publication_path(@basic_publication) %> |
<%= link_to 'Voltar', profile_path(@basic_publication.profile) %>