config/routes.rb
Rails.application.routes.draw do

  resources :eventos

  resources :editoras
  
  resources :basic_publications, :path => 'publications'

  resources :profiles do
    resources :basic_publications, :path => 'publications'
  end

  get 'pages/home'

  get 'pages/help'

  devise_for :users

  root 'pages#home'

end

app/models/editora.rb
class Editora < ActiveRecord::Base
    has_many :evento
end

app/controllers/editoras_controller.rb
class EditorasController < ApplicationController
  before_action :set_editora, only: [:show, :edit, :update, :destroy]

  # GET /editoras
  # GET /editoras.json
  def index
    @editoras = Editora.all
  end

  # GET /editoras/1
  # GET /editoras/1.json
  def show
  end

  # GET /editoras/new
  def new
    @editora = Editora.new
  end

  # GET /editoras/1/edit
  def edit
  end

  # POST /editoras
  # POST /editoras.json
  def create
    @editora = Editora.new(editora_params)

    respond_to do |format|
      if @editora.save
        format.html { redirect_to @editora, notice: 'Editora was successfully created.' }
        format.json { render :show, status: :created, location: @editora }
      else
        format.html { render :new }
        format.json { render json: @editora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editoras/1
  # PATCH/PUT /editoras/1.json
  def update
    respond_to do |format|
      if @editora.update(editora_params)
        format.html { redirect_to @editora, notice: 'Editora was successfully updated.' }
        format.json { render :show, status: :ok, location: @editora }
      else
        format.html { render :edit }
        format.json { render json: @editora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editoras/1
  # DELETE /editoras/1.json
  def destroy
    @editora.destroy
    respond_to do |format|
      format.html { redirect_to editoras_url, notice: 'Editora was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editora
      @editora = Editora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def editora_params
      params.require(:editora).permit(:nome, :cidade)
    end
end

app/helpers/editoras_helper.rb
module EditorasHelper
end

app/views/editoras/_form.html.erb
<%= form_for(@editora) do |f| %>
  <% if @editora.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editora.errors.count, "error") %> prohibited this editora from being saved:</h2>

      <ul>
      <% @editora.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editoras/edit.html.erb
<h1>Editing editora</h1>

<%= render 'form' %>

<%= link_to 'Show', @editora %> |
<%= link_to 'Back', editoras_path %>

app/views/editoras/index.html.erb
<h1>Listing editoras</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editoras.each do |editora| %>
      <tr>
        <td><%= editora.nome %></td>
        <td><%= editora.cidade %></td>
        <td><%= link_to 'Show', editora %></td>
        <td><%= link_to 'Edit', edit_editora_path(editora) %></td>
        <td><%= link_to 'Destroy', editora, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Editora', new_editora_path %>

app/views/editoras/new.html.erb
<h1>New editora</h1>

<%= render 'form' %>

<%= link_to 'Back', editoras_path %>

app/views/editoras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @editora.nome %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @editora.cidade %>
</p>

<%= link_to 'Edit', edit_editora_path(@editora) %> |
<%= link_to 'Back', editoras_path %>