config/routes.rb
Rails.application.routes.draw do

  resources :eventos

  resources :editoras
  
  resources :basic_publications, :path => 'publications'

  resources :profiles do
    resources :basic_publications, :path => 'publications'
  end

  get 'pages/home'

  get 'pages/help'

  devise_for :users

  root 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user  
  has_many :basic_publications
  
  def name
    self.first_name + " " + self.last_name 
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @publications = @profile.basic_publications
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @user = current_user
  end

  # GET /profiles/1/edit
  def edit    
    @user = current_user
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :first_name, :last_name, :phone, :email, :address, :institution, :job, :webpage, :citation_name, :areas_of_interest, :additional_information)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.number_field :user_id, :class => 'hidden', :value => @user.id %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :institution %><br>
    <%= f.text_field :institution, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :job %><br>
    <%= f.text_field :job, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :webpage %><br>
    <%= f.text_field :webpage, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :citation_name %><br>
    <%= f.text_field :citation_name, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :areas_of_interest %><br>
    <%= f.text_area :areas_of_interest, :class => "input-xlarge" %>
  </div>
  <div class="field">
    <%= f.label :additional_information %><br>
    <%= f.text_area :additional_information, :class => "input-xlarge" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_profile_info.html.erb
	<h2>
	  <strong>
	  	<%= @profile.first_name %> <%= @profile.last_name %>
	  </strong>
	</h2>	
	<hr />	
	<div class="row-fluid section-header">
		<h3 class="span6">Informações:</h3>
		<div class="span6">
			<%= link_to 'Editar perfil', edit_profile_path(@profile), :class => "btn btn-primary pull-right" %>
		</div>
	</div>	
	<p>
	  <strong>Telefone:</strong>
	  <%= @profile.phone %>
	</p>	
	<p>
	  <strong>Email:</strong>
	  <%= @profile.email %>
	</p>	
	<p>
	  <strong>Endereço:</strong>
	  <%= @profile.address %>
	</p>	
	<p>
	  <strong>Instituição:</strong>
	  <%= @profile.institution %>
	</p>	
	<p>
	  <strong>Cargo:</strong>
	  <%= @profile.job %>
	</p>	
	<p>
	  <strong>Página pessoal:</strong>
	  <%= @profile.webpage %>
	</p>	
	<p>
	  <strong>Nome para citação:</strong>
	  <%= @profile.citation_name %>
	</p>	
	<p>
	  <strong>Áreas de interesse:</strong>
	  <%= @profile.areas_of_interest %>
	</p>	
	<p>
	  <strong>Outras informações:</strong>
	  <%= @profile.additional_information %>
	</p>	
	

app/views/profiles/edit.html.erb
<h1>Editar perfil</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @profile %> |
<%= link_to 'Voltar', profiles_path %>

app/views/profiles/index.html.erb
<h2>Pesquisadores</h2>

<table class="table table-striped">
  <thead>
    <tr>      
      <th>Nome</th>      
      <th>Email</th>      
      <th class="table-actions"> </th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>        
        <td><%= profile.first_name %> <%= profile.last_name %></td>        
        <td><%= profile.email %></td>
        <td class="table-actions">
        	<%= link_to 'Mostrar', profile %>
        	<%= link_to '| Editar ', edit_profile_path(profile) %>
        	<%= link_to '| Deletar', profile, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1>Novo perfil:</h1>
<h4>Por favor preencha os dados de seu perfil:</h4>

<%= render 'form' %>

<%= link_to 'Voltar', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="profile_show_info">
	<%= render partial: "profile_info" %>	
</div>
<div id="profile_show_publications">
	<%= render partial: "/basic_publications/publication_info" %>
</div>