config/routes.rb
Rails.application.routes.draw do

  resources :eventos

  resources :editoras
  
  resources :basic_publications, :path => 'publications'

  resources :profiles do
    resources :basic_publications, :path => 'publications'
  end

  get 'pages/home'

  get 'pages/help'

  devise_for :users

  root 'pages#home'

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :editora
  belongs_to :user
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:titulo, :ano, :pais, :idioma, :home_page, :titulo_ingles, :nome_evento, :cidade_evento, :ano_realizacao, :titulo_anais, :volume, :fasciculo, :serie, :pagina_inicial, :pagina_final, :isbn, :editora_id, :user_id)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :pais %><br>
    <%= f.text_field :pais %>
  </div>
  <div class="field">
    <%= f.label :idioma %><br>
    <%= f.text_field :idioma %>
  </div>
  <div class="field">
    <%= f.label :home_page %><br>
    <%= f.text_field :home_page %>
  </div>
  <div class="field">
    <%= f.label :titulo_ingles %><br>
    <%= f.text_field :titulo_ingles %>
  </div>
  <div class="field">
    <%= f.label :nome_evento %><br>
    <%= f.text_field :nome_evento %>
  </div>
  <div class="field">
    <%= f.label :cidade_evento %><br>
    <%= f.text_field :cidade_evento %>
  </div>
  <div class="field">
    <%= f.label :ano_realizacao %><br>
    <%= f.number_field :ano_realizacao %>
  </div>
  <div class="field">
    <%= f.label :titulo_anais %><br>
    <%= f.text_field :titulo_anais %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :fasciculo %><br>
    <%= f.text_field :fasciculo %>
  </div>
  <div class="field">
    <%= f.label :serie %><br>
    <%= f.text_field :serie %>
  </div>
  <div class="field">
    <%= f.label :pagina_inicial %><br>
    <%= f.number_field :pagina_inicial %>
  </div>
  <div class="field">
    <%= f.label :pagina_final %><br>
    <%= f.number_field :pagina_final %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :editora %><br>	
	<%= select("evento", "editora_id", Editora.all.collect {|p| [ p.nome, p.id ] }, { include_blank: true })%>    
  </div>
  <div class="field">
    <%= f.label :user %><br>	
	<%= select("evento", "user_id", User.all.collect {|p| [ p.profile.citation_name, p.id ] }, { include_blank: true })%>    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Ano</th>
      <th>Nome evento</th>
      <th>Editora</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.titulo %></td>
        <td><%= evento.ano %></td>	
        <td><%= evento.nome_evento %></td>
        <td><%= evento.editora.nome %></td>
        <td><%= evento.user.profile.citation_name %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @evento.titulo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @evento.ano %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @evento.pais %>
</p>

<p>
  <strong>Idioma:</strong>
  <%= @evento.idioma %>
</p>

<p>
  <strong>Home page:</strong>
  <%= @evento.home_page %>
</p>

<p>
  <strong>Titulo ingles:</strong>
  <%= @evento.titulo_ingles %>
</p>

<p>
  <strong>Nome evento:</strong>
  <%= @evento.nome_evento %>
</p>

<p>
  <strong>Cidade evento:</strong>
  <%= @evento.cidade_evento %>
</p>

<p>
  <strong>Ano realizacao:</strong>
  <%= @evento.ano_realizacao %>
</p>

<p>
  <strong>Titulo anais:</strong>
  <%= @evento.titulo_anais %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @evento.volume %>
</p>

<p>
  <strong>Fasciculo:</strong>
  <%= @evento.fasciculo %>
</p>

<p>
  <strong>Serie:</strong>
  <%= @evento.serie %>
</p>

<p>
  <strong>Pagina inicial:</strong>
  <%= @evento.pagina_inicial %>
</p>

<p>
  <strong>Pagina final:</strong>
  <%= @evento.pagina_final %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @evento.isbn %>
</p>

<p>
  <strong>Editora:</strong>
  <%= @evento.editora.nome %>
</p>

<p>
  <strong>User:</strong>
  <%= @evento.user.profile.citation_name %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>